"""
03_report_generation/make_paper2_mosaic_map.py  (2026-08-23)

Paper 2's final figure: one national-extent 3-class accessibility map,
assembled from the already-computed per-unit rasters in
results/grids/paper2_region_grids.pkl (no refitting -- reuses that pickle's
`cls`/`lon2d`/`lat2d` per unit directly).

Zone-composition decisions (per user's explicit call, 2026-08-23: "for the
south, use the best one out of duo+eddakhla independent or full trio, same
for casa+rabat" -- a single choice per zone, not per-target):

  South (Guelmim-Oued Noun + Laâyoune-Sakia El Hamra + Eddakhla-Oued Eddahab):
    Re-run at N=1{,}662 (02_modeling_and_analysis/27, per-site OOF, restricted
    to Eddakhla's own 34 sites, the fair apples-to-apples test) after fixing
    a hardcoded-threshold-0.5 bug that had corrupted the Easy comparison
    (see results/json/other/phase5_paper2_eddakhla_zone_comparison.json):
      Difficult: eddakhla-standalone 0.8235 vs trio-on-eddakhla 0.8529 -> trio
      Easy:      eddakhla-standalone 0.8824 vs trio-on-eddakhla 0.9118 -> trio
      (pre-fix, the Easy trio number was wrongly 0.7647, making it look like
      standalone won; the correct tuned threshold reverses that.)
    -> DECISION: full trio for BOTH targets. This is a change from the
       original N=939-era decision (independent kept, exact tie) -- at
       N=1{,}662 the trio genuinely wins both targets, not a tie, so
       "south_duo" + "eddakhla" as two separate mosaic units is replaced by
       the single "south_trio" unit below.

  Rabat-Salé-Kénitra + Grand Casablanca-Settat:
    Re-run at N=1{,}662 (02_modeling_and_analysis/28, same threshold-bug fix
    and, separately, a fix removing a hardcoded "Rabat-Difficult is always
    degenerate standalone" shortcut that no longer held once the region grew
    past n_pos=3): Rabat-Salé-Kénitra now supports a real standalone fit for
    both targets.
      Difficult: Rabat-standalone 0.9091 vs merged-on-Rabat 0.9091 -> tie,
                 defaults to standalone.
      Easy:      Rabat-standalone 0.7500 vs merged-on-Rabat 0.7045 -> standalone
                 wins by +4.55pp (previously reported, incorrectly, as an
                 exact tie).
    -> DECISION: standalone Rabat-Salé-Kénitra is now the stronger option on
       both targets it can be tested on, but Casablanca-Settat itself still
       has no standalone fit (N=14, still the thinnest constituent) and so
       cannot be shown on its own; the merged "rabatcasa" unit is kept for
       the mosaic because it is the only configuration with full coverage of
       both territories, at a documented, small (Easy) or zero (Difficult)
       accuracy cost restricted to Rabat's own sites.

Oriental had zero labeled sites in the original N=939 catalog; the third
labeling batch added 4 (still 0 Difficult), too few to model or merge as its
own region. Per explicit user request (2026-09-01), Oriental is no longer
shown as flat "no data": its territory is projected using the NATIONAL
deployed models instead (GP+Infra for Difficult, Tree+Infra for Easy, from
the national companion paper's results/grids/map_grids.pkl), the same models
every OTHER region in this paper deliberately does NOT use, because a
national model pools terrain relationships that don't hold uniformly
everywhere -- exactly the motivation for this whole regional paper. This is
disclosed as a fallback of last resort, not a regional result: checked
against Oriental's own 4 labeled sites (each scored by refitting only the
specific national-model CV fold that left it out, a genuine out-of-fold
prediction, not the model grading its own training data), only 1 of 4 (25%)
is correctly classified -- worse than guessing the local majority class (2
Easy, 2 Moderate -> 50%). The projection is shown anyway, visually
distinguished with a dot-hatch overlay and a lighter fill, because a poor
but disclosed national-model guess is still more informative than an
unlabeled blank, and the reader is given the real number to judge it by
(see oriental_national_model_check.csv, generated by a one-off script,
results reused here directly).

Revised 2026-08-23 alongside make_paper2_region_maps.py after user review:
same three fixes ported here (this script had the identical bugs, since it
was written from the same first-draft pattern): (1) misclassification ring
truth now comes from 02_modeling_and_analysis/29's exact per-site LOGO-cluster CV OOF
predictions, not a coarse nearest-grid-cell raster lookup; (2) each unit's
raster is clipped to its own exact polygon boundary so no color bleeds past
the true region shape; (3) all 939 points at national scale are far denser
than any single region map, so declutter_points/auto_min_dist_km (ported
from make_maps_render.py, Paper 1's own established fix for this) is applied
here too, per-unit so a crowded corridor in one region doesn't starve
thinning budget from a sparser region elsewhere.

Output: report/figures/map_national_mosaic.pdf
"""
import math, os, glob, pickle, warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import geopandas as gpd
from pyproj import Geod

import matplotlib
# Native PDF backend, not PGF/LaTeX -- this figure clips 9 units' rasters to
# their own real (detailed-coastline) polygon boundaries, and PGF renders
# every clip path as LaTeX drawing commands: with this many high-vertex-count
# paths in one figure, pdflatex overflows ("TeX capacity exceeded"), the same
# class of failure the Morocco reference map hit and was fixed the same way.
matplotlib.use("pdf")
import matplotlib.pyplot as plt
plt.rcParams.update({"font.family": "serif", "font.size": 9})
from matplotlib.colors import ListedColormap, BoundaryNorm
from matplotlib.patches import Patch, PathPatch
from matplotlib.path import Path as MplPath
from matplotlib.lines import Line2D

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.abspath(os.path.join(HERE, ".."))
OUT = os.path.join(HERE, "..", "report", "figures")
GRID_DIR = os.path.join(FW, "results", "grids")

EASY_COL, MODERATE_COL, DIFFICULT_COL = "#76A5AF", "#E5D3A7", "#C1650A"
BOUND_COL = "#2B5F72"
NODATA_COL = "#D9D9D6"
MARKER, MARKER_EDGE = "o", "black"
POINT_COLORS = {"Easy": EASY_COL, "Moderate": MODERATE_COL, "Difficult": DIFFICULT_COL}
POINT_S = 13  # was 5 -- at national scale the old size was nearly invisible
CLASS_TO_INT = {"Easy": 0, "Moderate": 1, "Difficult": 2}
GEOD = Geod(ellps="WGS84")

def boundary_clip_patch(gdf_row_geom):
    # Exterior rings ONLY -- see make_paper2_region_maps.py's boundary_clip_patch
    # docstring: union_all() on a merged unit's two source polygons leaves
    # degenerate sliver "holes" along their shared seam, which rendered as a
    # blank gap over a whole sub-region when included as clip-path holes.
    union = gdf_row_geom
    geoms = [union] if union.geom_type != "MultiPolygon" else list(union.geoms)
    verts, codes = [], []
    for geom in geoms:
        xy = np.array(geom.exterior.coords)
        verts.extend(xy.tolist())
        codes.extend([MplPath.MOVETO] + [MplPath.LINETO] * (len(xy) - 2) + [MplPath.CLOSEPOLY])
    return MplPath(verts, codes)

def declutter_points(lat, lon, min_dist_km):
    lat, lon = np.asarray(lat), np.asarray(lon)
    kept_lat, kept_lon = [], []
    keep_mask = np.zeros(len(lat), dtype=bool)
    for i in range(len(lat)):
        if not kept_lat:
            keep_mask[i] = True
            kept_lat.append(lat[i]); kept_lon.append(lon[i])
            continue
        d = np.asarray(GEOD.inv(np.full(len(kept_lon), lon[i]), np.full(len(kept_lat), lat[i]),
                                 kept_lon, kept_lat)[2]) / 1000.0
        if d.min() >= min_dist_km:
            keep_mask[i] = True
            kept_lat.append(lat[i]); kept_lon.append(lon[i])
    return keep_mask

def auto_min_dist_km(bounds, fig_width_in, marker_s, safety=1.3):
    minx, miny, maxx, maxy = bounds
    clat = (miny + maxy) / 2
    _, _, span_m = GEOD.inv(minx, clat, maxx, clat)
    km_per_point = (span_m / 1000 / fig_width_in) / 72.0
    marker_diam_pts = 2 * math.sqrt(marker_s / math.pi)
    return marker_diam_pts * km_per_point * safety

DECLUTTER_N_THRESHOLD = 60

all_grids = pickle.load(open(os.path.join(GRID_DIR, "paper2_region_grids.pkl"), "rb"))

MOSAIC_UNITS = ["fesmeknes", "bmk", "ttah", "draa", "soussmassa", "marrakech", "south_trio", "rabatcasa"]
# south_duo/eddakhla-standalone excluded from the mosaic now that the trio
# decision (both targets) supersedes them -- see docstring above. Their own
# standalone maps still appear in the paper's region-detail section.

REGION_TO_UNIT = {
    "Fés-Meknés": "fesmeknes", "Béni Mellal-Khénifra": "bmk", "Tanger-Tétouan-Al Hoceima": "ttah",
    "Drâa-Tafilalet": "draa", "Souss-Massa": "soussmassa", "Marrakech-Safi": "marrakech",
    "Eddakhla-Oued Eddahab": "south_trio", "Guelmim-Oued Noun": "south_trio", "Laayoune-Sakia El Hamra": "south_trio",
    "Rabat-Salé-Kénitra": "rabatcasa", "Grand Casablanca-Settat": "rabatcasa",
}

admin12 = gpd.read_file(os.path.join(FW, "data/boundaries/morocco_regions_admin12.geojson"))
oriental = admin12[admin12["nom_region"] == "Oriental"]

# --- Oriental: project from the NATIONAL deployed models (GP+Infra Difficult,
# Tree+Infra Easy), reusing the already-computed national grid from Paper 1's
# own map (results/grids/map_grids.pkl) -- see module docstring for why this
# is a disclosed fallback, not a regional result like every other zone here.
_national_grids = pickle.load(open(os.path.join(GRID_DIR, "map_grids.pkl"), "rb"))
_nat = _national_grids["results"]["national"]
_ox0, _oy0, _ox1, _oy1 = oriental.total_bounds
_margin = 0.15
_omask_x = (_nat["lon2d"][0, :] >= _ox0 - _margin) & (_nat["lon2d"][0, :] <= _ox1 + _margin)
_omask_y = (_nat["lat2d"][:, 0] >= _oy0 - _margin) & (_nat["lat2d"][:, 0] <= _oy1 + _margin)
oriental_grid = dict(
    lon2d=_nat["lon2d"][np.ix_(_omask_y, _omask_x)],
    lat2d=_nat["lat2d"][np.ix_(_omask_y, _omask_x)],
    cls=_nat["cls"][np.ix_(_omask_y, _omask_x)],
    bounds=(_nat["lon2d"][0, _omask_x].min(), _nat["lat2d"][_omask_y, 0].min(),
            _nat["lon2d"][0, _omask_x].max(), _nat["lat2d"][_omask_y, 0].max()),
)
oriental_check = pd.read_csv(os.path.join(FW, "results/json/other/oriental_national_model_check.csv"))
oriental_n_correct = int(oriental_check["correct"].sum())
oriental_n_total = len(oriental_check)
print(f"Oriental national-model projection: {oriental_n_correct}/{oriental_n_total} labeled sites correctly classified")

# --- labeled sites for the overlay (same convention as every other map) ---
catalog = pd.read_csv(os.path.join(FW, "data/final/geosites_mcdm_national.csv"))
frames = []
for f in sorted(glob.glob(os.path.join(FW, "data/final/regional_label_sources/*.csv"))):
    bn = os.path.basename(f)
    if "expert_labels" not in bn or "combined" in bn:
        continue
    df = pd.read_csv(f)
    labeled = df[df["Expert_Class"].notna() & (df["Expert_Class"] != "")].copy()
    frames.append(labeled[["Locality_ID", "Expert_Class"]])
all_labels = pd.concat(frames, ignore_index=True).drop_duplicates("Locality_ID")
sites = all_labels.merge(catalog[["Locality_ID", "Region", "Latitude_WGS84", "Longitude_WGS84"]], on="Locality_ID", how="inner")
sites = sites.dropna(subset=["Region"]).reset_index(drop=True)
sites["Expert_Merged"] = sites["Expert_Class"].replace("Very Difficult", "Difficult")
sites["unit"] = sites["Region"].map(REGION_TO_UNIT)
oriental_sites = sites[sites["Region"] == "Oriental"].copy()  # kept separately: not part of any MOSAIC_UNITS declutter loop, only 4 sites, no thinning needed
sites = sites[sites["unit"].notna()].reset_index(drop=True)

# No per-site misclassification overlay at national scale, by design (user
# decision, 2026-08-23): at 939 points across the whole country, per-site
# correctness rings read as a visual accuracy VERDICT that doesn't match the
# real per-region numbers (dense red clusters make good models look bad at a
# glance), and the exact figures are already reported per region in the
# tables/text. This map's job is where sites are and their predicted zone;
# the per-region maps (which show correctness at a legible scale, thinned to
# match true accuracy) carry the correctness detail.
print(f"National mosaic: {len(sites)} sites overlaid (true class only, no misclassification overlay)")

# Declutter per unit (each unit's own point set), then combine -- avoids a
# crowded corridor in one region starving the thinning budget of a sparser
# region elsewhere. The matplotlib CANVAS is 7in wide (below, for resolution),
# but the LaTeX report includes this figure at \includegraphics[width=0.62\linewidth]
# on a 160mm (6.30in) text width -- a PRINTED width of ~3.91in.
#
# Critically, the km-per-printed-point conversion must be computed from the
# WHOLE NATIONAL MAP's bounding box, not each unit's own (much smaller) bbox:
# every point shares the same physical scale on this one combined map (a
# region occupies only a fraction of the printed width, not all of it), so
# passing a unit's own bounds into auto_min_dist_km() understated the true
# on-page scale by roughly (unit width / national width) -- for a region like
# Fes-Meknes that is a large factor, and is why points kept visibly
# overlapping there even after the printed-width fix above (flagged
# 2026-09-01). One global min_dist_km, from the national bounds, is correct
# and is reused for every unit below.
FIG_WIDTH_IN = 7.0
PRINTED_FIG_WIDTH_IN = 160 / 25.4 * 0.62  # 0.62\linewidth on a 160mm textwidth page
GLOBAL_MIN_DIST_KM = auto_min_dist_km(admin12.total_bounds, PRINTED_FIG_WIDTH_IN, POINT_S)
draw_frames = []
for key in MOSAIC_UNITS:
    u = all_grids[key]
    unit_sites = sites[sites["unit"] == key].copy()
    if len(unit_sites) > DECLUTTER_N_THRESHOLD:
        keep = declutter_points(unit_sites["Latitude_WGS84"].values, unit_sites["Longitude_WGS84"].values, GLOBAL_MIN_DIST_KM)
        unit_sites = unit_sites[keep]
    draw_frames.append(unit_sites)
draw_frames.append(oriental_sites)
sites_draw = pd.concat(draw_frames, ignore_index=True) if draw_frames else sites.iloc[0:0]
print(f"  declutter: showing {len(sites_draw)}/{len(sites) + len(oriental_sites)} markers total")

# --- render ---
minx, miny, maxx, maxy = admin12.total_bounds
fig, ax = plt.subplots(figsize=(FIG_WIDTH_IN, 8.6))
ax.set_facecolor("white")

cmap = ListedColormap([EASY_COL, MODERATE_COL, DIFFICULT_COL])
norm = BoundaryNorm([-0.5, 0.5, 1.5, 2.5], cmap.N)

unit_images = []  # (im, clip_path) pairs -- clip applied after tight_layout, see below
for key in MOSAIC_UNITS:
    u = all_grids[key]
    ux0, uy0, ux1, uy1 = u["bounds"]
    cls_masked = np.ma.masked_where(u["cls"] < 0, u["cls"])
    cls_hi = np.repeat(np.repeat(cls_masked, 4, axis=0), 4, axis=1)  # nearest-upsample -- see make_paper2_region_maps.py's upsample_nearest for why
    im = ax.imshow(cls_hi, extent=(ux0, ux1, uy0, uy1), origin="lower", cmap=cmap, norm=norm,
                    alpha=0.85, zorder=2, interpolation="nearest")
    unit_images.append((im, boundary_clip_patch(u["gdf"].union_all())))

# Oriental: projected from the NATIONAL model (fallback, not region-specific --
# see docstring), rendered at reduced alpha with a dot-hatch overlay so it
# reads visually as provisional, distinct from every other zone's real
# region-specific fit.
if len(oriental):
    ox0, oy0, ox1, oy1 = oriental_grid["bounds"]
    ocls_masked = np.ma.masked_where(oriental_grid["cls"] < 0, oriental_grid["cls"])
    ocls_hi = np.repeat(np.repeat(ocls_masked, 4, axis=0), 4, axis=1)
    oim = ax.imshow(ocls_hi, extent=(ox0, ox1, oy0, oy1), origin="lower", cmap=cmap, norm=norm,
                     alpha=0.5, zorder=2, interpolation="nearest")
    unit_images.append((oim, boundary_clip_patch(oriental.geometry.iloc[0])))
    oriental.plot(ax=ax, facecolor="none", edgecolor=BOUND_COL, linewidth=1.0, hatch="....", zorder=4)
    c = oriental.geometry.iloc[0].representative_point()
    ax.annotate(f"Oriental\n({oriental_n_correct}/{oriental_n_total} correct)*", (c.x, c.y), ha="center", va="center",
                fontsize=6.5, color="#333333", style="italic", zorder=6,
                bbox=dict(boxstyle="round,pad=0.25", facecolor="white", edgecolor="none", alpha=0.75))

admin12.boundary.plot(ax=ax, edgecolor=BOUND_COL, linewidth=1.1, zorder=3)

for cls_name in ["Moderate", "Easy", "Difficult"]:
    pts = sites_draw[sites_draw["Expert_Merged"] == cls_name]
    if len(pts) == 0:
        continue
    ax.scatter(pts["Longitude_WGS84"], pts["Latitude_WGS84"], marker=MARKER, s=POINT_S,
               facecolor=POINT_COLORS[cls_name], edgecolor=MARKER_EDGE, linewidth=0.5, zorder=5)

ax.set_xlim(minx - 0.3, maxx + 0.3)
ax.set_ylim(miny - 0.3, maxy + 0.3)
ax.set_xticks([]); ax.set_yticks([])
for spine in ax.spines.values():
    spine.set_edgecolor("#888888"); spine.set_linewidth(0.6)

class_handles = [Patch(facecolor=EASY_COL, label="Predicted Easy"), Patch(facecolor=MODERATE_COL, label="Predicted Moderate"),
                 Patch(facecolor=DIFFICULT_COL, label="Predicted Difficult"),
                 Patch(facecolor="none", edgecolor=BOUND_COL, hatch="....", label="Oriental (national-model fallback)")]
point_handles = [Line2D([0], [0], marker=MARKER, color="none", markerfacecolor=POINT_COLORS[c],
                         markeredgecolor=MARKER_EDGE, markeredgewidth=0.5, markersize=8,
                         label=f"True {c.lower()} site") for c in ["Easy", "Moderate", "Difficult"]]
ax.legend(handles=class_handles + point_handles, loc="upper center", bbox_to_anchor=(0.5, -0.02),
          ncol=3, fontsize=7, frameon=True, framealpha=0.92, edgecolor="#cccccc", borderpad=0.6,
          handletextpad=0.5, labelspacing=0.45, columnspacing=1.0)

plt.tight_layout()
# Clip applied AFTER tight_layout -- see make_paper2_region_maps.py for the full
# explanation. tight_layout repositions the axes for the below-anchored legend;
# a clip_path set before that (per unit, in the loop above) clips at the stale
# pre-tight_layout axes position at save time, silently blanking part of a
# unit's true shape -- confirmed by bisecting the render with intermediate
# savefig() checkpoints on the per-region map script that shares this pattern.
for im, clip_path in unit_images:
    im.set_clip_path(PathPatch(clip_path, transform=ax.transData))
out_path = os.path.join(OUT, "map_national_mosaic.pdf")
plt.savefig(out_path, bbox_inches="tight", pad_inches=0.15)
plt.close(fig)
print(f"Saved {out_path}")
